/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MerAlert: typeof import('./src/components/MerAlert.vue')['default']
    MerButton: typeof import('./src/components/MerButton.vue')['default']
    MerText: typeof import('./src/components/MerText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SolarArrowDownLinear: typeof import('~icons/solar/arrow-down-linear')['default']
    SolarCloseCircleLinear: typeof import('~icons/solar/close-circle-linear')['default']
    SolarCloudUploadLinear: typeof import('~icons/solar/cloud-upload-linear')['default']
    SolarInfoCircleLinear: typeof import('~icons/solar/info-circle-linear')['default']
    SolarMaximizeLinear: typeof import('~icons/solar/maximize-linear')['default']
    SolarMinimizeLinear: typeof import('~icons/solar/minimize-linear')['default']
    SolarPauseLinear: typeof import('~icons/solar/pause-linear')['default']
    SolarPlayLinear: typeof import('~icons/solar/play-linear')['default']
    SolarTrashBin2Linear: typeof import('~icons/solar/trash-bin2-linear')['default']
  }
}
