/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MerAlert: typeof import('./src/components/MerAlert.vue')['default']
    MerButton: typeof import('./src/components/MerButton.vue')['default']
    MerText: typeof import('./src/components/MerText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SolarCloseCircleBoldDuotone: typeof import('~icons/solar/close-circle-bold-duotone')['default']
    SolarCloseCircleBroken: typeof import('~icons/solar/close-circle-broken')['default']
    SolarCloseCircleLinear: typeof import('~icons/solar/close-circle-linear')['default']
    SolarCloseCircleLineDuotone: typeof import('~icons/solar/close-circle-line-duotone')['default']
    SolarCloseCircleOutline: typeof import('~icons/solar/close-circle-outline')['default']
    SolarCloudUploadBoldDuotone: typeof import('~icons/solar/cloud-upload-bold-duotone')['default']
    SolarCloudUploadBroken: typeof import('~icons/solar/cloud-upload-broken')['default']
    SolarCloudUploadLinear: typeof import('~icons/solar/cloud-upload-linear')['default']
    SolarCloudUploadLineDuotone: typeof import('~icons/solar/cloud-upload-line-duotone')['default']
    SolarCloudUploadOutline: typeof import('~icons/solar/cloud-upload-outline')['default']
    SolarInfoCircleBoldDuotone: typeof import('~icons/solar/info-circle-bold-duotone')['default']
    SolarInfoCircleBroken: typeof import('~icons/solar/info-circle-broken')['default']
    SolarInfoCircleLinear: typeof import('~icons/solar/info-circle-linear')['default']
    SolarInfoCircleLineDuotone: typeof import('~icons/solar/info-circle-line-duotone')['default']
    SolarInfoCircleOutline: typeof import('~icons/solar/info-circle-outline')['default']
    SolarMaximizeBoldDuotone: typeof import('~icons/solar/maximize-bold-duotone')['default']
    SolarMaximizeBroken: typeof import('~icons/solar/maximize-broken')['default']
    SolarMaximizeLinear: typeof import('~icons/solar/maximize-linear')['default']
    SolarMaximizeLineDuotone: typeof import('~icons/solar/maximize-line-duotone')['default']
    SolarMaximizeOutline: typeof import('~icons/solar/maximize-outline')['default']
    SolarMinimizeBoldDuotone: typeof import('~icons/solar/minimize-bold-duotone')['default']
    SolarMinimizeBroken: typeof import('~icons/solar/minimize-broken')['default']
    SolarMinimizeLinear: typeof import('~icons/solar/minimize-linear')['default']
    SolarMinimizeLineDuotone: typeof import('~icons/solar/minimize-line-duotone')['default']
    SolarMinimizeOutline: typeof import('~icons/solar/minimize-outline')['default']
    SolarPauseBoldDuotone: typeof import('~icons/solar/pause-bold-duotone')['default']
    SolarPauseBroken: typeof import('~icons/solar/pause-broken')['default']
    SolarPauseLinear: typeof import('~icons/solar/pause-linear')['default']
    SolarPauseLineDuotone: typeof import('~icons/solar/pause-line-duotone')['default']
    SolarPauseOutline: typeof import('~icons/solar/pause-outline')['default']
    SolarPlayBoldDuotone: typeof import('~icons/solar/play-bold-duotone')['default']
    SolarPlayBroken: typeof import('~icons/solar/play-broken')['default']
    SolarPlayLinear: typeof import('~icons/solar/play-linear')['default']
    SolarPlayLineDuotone: typeof import('~icons/solar/play-line-duotone')['default']
    SolarPlayOutline: typeof import('~icons/solar/play-outline')['default']
    SolarTrashBin2BoldDuotone: typeof import('~icons/solar/trash-bin2-bold-duotone')['default']
    SolarTrashBin2Broken: typeof import('~icons/solar/trash-bin2-broken')['default']
    SolarTrashBin2Linear: typeof import('~icons/solar/trash-bin2-linear')['default']
    SolarTrashBin2LineDuotone: typeof import('~icons/solar/trash-bin2-line-duotone')['default']
    SolarTrashBin2Outline: typeof import('~icons/solar/trash-bin2-outline')['default']
  }
}
